aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from jobs.views import ApplicationList, ApplicationRetrieveDestroy
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
    path('api/applications', ApplicationList.as_view()),
    path('api/applications/<int:pk>', ApplicationRetrieveDestroy.as_view()),
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('jobs.urls', namespace='jobs')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('careers/', include('careers.urls', namespace='careers')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

blogs/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('stories_and_blogs/', views.stories_and_blogs, name='stories_and_blogs'),
    path('teams/', views.teams, name='teams'),


    path('stories/', views.stories_list, name='story'),
    path('story_detail/<int:id>', views.stories_detail, name='stories_detail'),

    # api
    path('api/stories', api.stories_api, name='stories_api'),
    path('api/stories/<int:id>', api.story_detail_api, name='story_detail_api'),


    # class based views
    path('api/v2/stories', api.StoryDetailListApi.as_view(),
         name='StoryDetailListApi'),
    path('api/v2/stories/<int:id>',
         api.StoryDetailDetail.as_view(), name='StoryDetailDetail'),
]

careers/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'careers'

urlpatterns = [
    path('careerlist/', views.career_list, name='career_list'),
    path('careerdetail/<int:id>', views.career_detail, name='career_detail'),

    # api
    path('api/careers', api.career_list_api, name='career_list_api'),
    path('api/careers/<int:id>', api.career_detail_api, name='career_detail_api'),
    path('api/careerForm/<str:carrer_name>', views.careerForm, name='careerForm'),

    # class based views
    path('api/v2/careers', api.CareerDetailListApi.as_view(), name='career_list_api'),
    path('api/v2/careers/<int:id>',
         api.CareerDetailDetail.as_view(), name='career_detail_api'),
]

jobs/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from . import views
from . import api

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('applicantsList/', views.applicantsList, name='applicantsList'),
    path('volunteer/', views.volunteerForm, name='volunteer'),
    path('reply/', views.reply, name='reply'),
    path('donate/', views.donate, name='donate'),
    path('contact/', views.contact, name='contact'),
    path('vision_mission_value/', views.vision_mission_value,
         name='vision_mission_value'),
    path('about/', views.about, name='about'),
    path('who_we_are/', views.who_we_are, name='who_we_are'),
    path('get_involved/', views.get_involved, name='get_involved'),
    
    path('what_we_are_doing/', views.what_we_are_doing, name='what_we_are_doing'),
    path('what_we_are_doing_details/<int:id>', views.what_we_are_doing_details,
         name='what_we_are_doing_details'),

    # api
    path('api/what_do', api.what_do_api, name='what_do_api'),
    path('api/what_do_detail/<int:id>',
         api.what_do_detail_api, name='what_do_detail_api'),

    # class based views
    path('api/v2/what_do', api.WhatWeAreDoingDetailListApi.as_view(),
         name='WhatWeAreDoingDetailListApi'),
    path('api/v2/what_do_detail/<int:id>',
         api.WhatWeAreDoingDetailDetail.as_view(), name='WhatWeAreDoingDetailDetail'),

]

careers/models.py
from django.db import models
from .validators import validate_image_extension
from datetime import date
from django.utils.translation import gettext_lazy as _

JOB_TYPE = (
    ('1', "Full time"),
    ('2', "Part time"),
    ('3', "Internship"),
)

JOB_TYPE_AR = (
    ('1', "دوام كامل"),
    ('2', "دوام جزئي"),
    ('3', "تدريب"),
)
class CareerDetail(models.Model):
   
    title = models.CharField(max_length=300, default='', null=True, blank=True)
    title_ar = models.CharField(max_length=300, default='', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    description_ar = models.TextField(null=True, blank=True)

    working_hours = models.CharField(
        max_length=300, default='', null=True, blank=True)
    contract_duration = models.CharField(
        max_length=300, default='', null=True, blank=True)
    governorate = models.CharField(
        max_length=300, default='', null=True, blank=True)
    governorate_ar = models.CharField(
        max_length=300, default='', null=True, blank=True)
    job_type = models.CharField(
        choices=JOB_TYPE, max_length=1, null=True, blank=True)
    job_type_ar = models.CharField(
        choices=JOB_TYPE_AR, max_length=1, null=True, blank=True)
    
    location = models.CharField(
        max_length=300, default='', null=True, blank=True)
    location_ar = models.CharField(
        max_length=300, default='', null=True, blank=True)
    posted = models.DateField(default=date.today, null=True, blank=True)
    minimum_education = models.CharField(
        max_length=300, default='', null=True, blank=True)
    minimum_education_ar = models.CharField(
        max_length=300, default='', null=True, blank=True)
    minimum_experience = models.CharField(
        max_length=300, default='', null=True, blank=True)
    required_travel = models.CharField(
        max_length=150, default='', null=True, blank=True)
    required_travel_ar = models.CharField(
        max_length=150, default='', null=True, blank=True)
    no_of_jobs = models.PositiveIntegerField(default=1, null=True, blank=True)
    deadline = models.DateField(default=date.today, null=True, blank=True)
    puplished = models.DateField(default=date.today, null=True, blank=True)
       # Roles and Resposibilities
    role_1 = models.TextField(null=True, blank=True)
    role_1_ar = models.TextField(null=True, blank=True)
    role_2 = models.TextField(null=True, blank=True)
    role_2_ar = models.TextField(null=True, blank=True)
    role_3 = models.TextField(null=True, blank=True)
    role_3_ar = models.TextField(null=True, blank=True)
    role_4 = models.TextField(null=True, blank=True)
    role_4_ar = models.TextField(null=True, blank=True)
    role_5 = models.TextField(null=True, blank=True)
    role_5_ar = models.TextField(null=True, blank=True)
    role_6 = models.TextField(null=True, blank=True)
    role_6_ar = models.TextField(null=True, blank=True)
    role_7 = models.TextField(null=True, blank=True)
    role_7_ar = models.TextField(null=True, blank=True)
    role_8 = models.TextField(null=True, blank=True)
    role_8_ar = models.TextField(null=True, blank=True)
    role_9 = models.TextField(null=True, blank=True)
    role_9_ar = models.TextField(null=True, blank=True)
    role_10 = models.TextField(null=True, blank=True)
    role_10_ar = models.TextField(null=True, blank=True)

   

    # Qualifications & Preferred Skills
    skill_1 = models.TextField(null=True, blank=True)
    skill_1_ar = models.TextField(null=True, blank=True)
    skill_2 = models.TextField(null=True, blank=True)
    skill_2_ar = models.TextField(null=True, blank=True)
    skill_3 = models.TextField(null=True, blank=True)
    skill_3_ar = models.TextField(null=True, blank=True)
    skill_4 = models.TextField(null=True, blank=True)
    skill_4_ar = models.TextField(null=True, blank=True)
    skill_5 = models.TextField(null=True, blank=True)
    skill_5_ar = models.TextField(null=True, blank=True)
    skill_6 = models.TextField(null=True, blank=True)
    skill_6_ar = models.TextField(null=True, blank=True)
    skill_7 = models.TextField(null=True, blank=True)
    skill_7_ar = models.TextField(null=True, blank=True)
    skill_8 = models.TextField(null=True, blank=True)
    skill_8_ar = models.TextField(null=True, blank=True)
    skill_9 = models.TextField(null=True, blank=True)
    skill_9_ar = models.TextField(null=True, blank=True)
    skill_10 = models.TextField(null=True, blank=True)
    skill_10_ar = models.TextField(null=True, blank=True)

    

    def __str__(self):
        return self.title


class CareerList(models.Model):
    image_bg_career_list = models.FileField(
        validators=[validate_image_extension], upload_to='background/career_list/', null=True, blank=True)


class CareerDetatilImage(models.Model):

    image_header_logo_sticky_career_detail_image = models.FileField(
        validators=[validate_image_extension], upload_to='background/career_detail_image/', null=True, blank=True)
    image_footer_logo_career_detail_image = models.FileField(
        validators=[validate_image_extension], upload_to='background/career_detail_image/', null=True, blank=True)

careers/views.py
from typing import List
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import CareerDetail, CareerList, CareerDetatilImage
from django.core.paginator import Paginator
from .form import CareerDetailForm
from django.urls import reverse
from django.http import HttpRequest
from .serializers import CareerDetailSerializer, CareerListSerializer, CareerDetatilImageSerializer
from .filters import CareerDetailFilter
from django.core.mail import send_mail,  EmailMessage


# Create your views here.


def career_list(request):
    career_list = CareerDetail.objects.all()
    assert isinstance(request, HttpRequest)
    queryset = CareerList.objects.all()
    serializer_class = CareerListSerializer(queryset, many=True)

    # filters
    myfilter = CareerDetailFilter(request.GET, queryset=career_list)
    career_list = myfilter.qs

    # Show many contacts per page.
    paginator = Paginator(career_list, 10000000000000000)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if career_list:
        context = {'careers': page_obj, 'myfilter': myfilter,
                   'data': serializer_class.data}  # template name

    else:
        context = {'message': "There are no jobs available at the moment."}
    return render(request, 'career_list.html', context)


def career_detail(request, id):
    career_detail = CareerDetail.objects.get(id=id)
    print(career_detail)
    assert isinstance(request, HttpRequest)
    queryset = CareerDetatilImage.objects.all()
    serializer_class = CareerDetatilImageSerializer(queryset, many=True)

    context = {'career': career_detail, 'data': serializer_class.data}
    return render(request, 'career_detail.html', context)
    
def careerForm(request,carrer_name):
    if request.method == 'POST':
        print("hello")
        name = request.POST.get('full_name')
        # career_name = request.POST.get('career_name')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        region = request.POST.get('region')
        address = request.POST.get('address')
        upload_cv = request.FILES.get('upload_cv')
        English = request.POST.get('English')
        Arabic = request.POST.get('Arabic')
        Kurdish = request.POST.get('Kurdish')
        languages = {"English": English,
        "Arabic":Arabic,
        "Kurdish":Kurdish
        }
        cover_letter = request.POST.get('cover_letter')
        # print(select_language)
        select_language = []

        for language in languages:
            print(language)
            if languages[language] != None:
                select_language.append(language)
        data = {
            'name': name,
            'carrer_name':carrer_name,
            'gender' : gender,
            'email' : email,
            'phone' : phone,
            'region' : region,

            'address': address,
            'upload_cv' : upload_cv,
            'select_language' : select_language,
            'cover_letter' : cover_letter,
        }
        print(data)
        message = ''' 
        New applicant :{}
        From: {}
        Career Name : {}
        Phone: {}
        Region: {}
        Gender: {}
        Address:{}
        CV: {}
        Language:{}
        Cover_letter: {}


        '''.format(data['name'], data['email'],data['carrer_name'], data['phone'], data['region'], data['gender'], data['address'], data['upload_cv'], data['select_language'], data['cover_letter'])

        if name and gender and email and carrer_name and phone and  region and address and   upload_cv  and cover_letter:
         
            email = EmailMessage(
                              data['carrer_name'],    
                              message,
                              'info@ashuor.org', ['hr@ashuor.org'],)
                          
            if request.FILES:
                            uploaded_file = request.FILES['upload_cv'] # file is the name value which you have provided in form for file field
                            email.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
                            email.send()
            #     send_mail(data['carrer_name'], message, from_email= 'representative@aifrd.org',recipient_list= ['hr@aifrd.org'],  fail_silently=False)
            #     send_mail.attach(message. attach.read(), )
            #     send_mail.send()
            # except  Exception as error:
            return HttpResponse('Invalid header found.')
    return render(request, 'formCareer.html')

careers/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="en">
 
<head>
  <meta charset="utf-8" />
  <title>{% trans  "Ashor Iraqi Foundation for Relief and Development" %}</title>
 
  <!-- Stylesheets -->
  <link href="{% static 'careers/css/bootstrap.css' %}" rel="stylesheet" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
  {% if LANGUAGE_CODE == 'en' %}<link href="{% static 'careers/css/style.css' %}" rel="stylesheet" />
                                  {% elif LANGUAGE_CODE == 'ar' %}<link href="{% static 'careers/css/style_arabic.css' %}" rel="stylesheet" />{% endif %}
  
  <!-- Responsive File -->
  <link href="{% static 'careers/css/responsive.css' %}" rel="stylesheet" />

  <link rel="shortcut icon" href="{% static 'careers/images/logo.jpg' %}" type="image/x-icon" />
  <!-- Responsive Settings -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  
</head>

<body>
  <div class="page-wrapper">
    <!-- Preloader -->
    <div class="preloader">
      <div class="icon"></div>
    </div>
        <!-- Main Header -->
       <header class="main-header header-style-one">
       
        <!-- Header Upper -->
        <div class="header-upper">
          <div class="auto-container">
            <div class="inner-container clearfix">
              <!--Logo-->
              <div class="logo-box">
                <div class="logo">
                  <a
                    href="{% url 'jobs:index' %}"
                    title="Ashor Iraqi Foundation for Relief and Development"
                    >
                    <img
                      src="{% static 'careers/images/logo.png' %}" height="10px"
                      alt="Ashor Iraqi Foundation for Relief and Development" 
                  />
                </a>
                </div>
              </div>

              <!--Nav Box-->
              <div class="nav-outer clearfix">
                <!--Mobile Navigation Toggler-->
                <div class="mobile-nav-toggler">
                  <span class="icon flaticon-menu-1"></span>
                </div>

                <!-- Main Menu -->
                <nav class="main-menu navbar-expand-md navbar-light">
                  <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                    <ul class="navigation clearfix">
                        <li class="current dropdown"><a href="{% url 'jobs:about' %}">{% trans "ABOUT AIFRD" %}</a>
                            <ul>
                              <li><a href="{% url 'jobs:who_we_are' %}">{% trans "WHO WE ARE" %}</a></li>
                              <li><a href="{% url 'blogs:teams' %}">{% trans "OUR TEAMS" %}</a></li>
                                <li><a href="{% url 'jobs:vision_mission_value' %}">{% trans "VISION & MISSION"  %}</a></li>
                            </ul>
                        </li>
                       
                        <li><a href="{% url 'jobs:what_we_are_doing' %}">{% trans "WHAT WE ARE DOING" %}</a></li>
    
                        <li class="dropdown"><a href="{% url 'blogs:stories_and_blogs' %}">{% trans "STORIES & BLOG" %}</a>
                          <ul>
                            <li><a href="{% url 'blogs:story' %}">{% trans  "OUR STORIES" %}</a></li>
                            <li><a href="{% url 'blogs:blogs' %}"> {% trans "OUR BLOGS" %}</a></li>
    
                          </ul>
                        </li>
                        <li class="dropdown"><a href="{% url 'jobs:get_involved' %}">{% trans "GET INVOLVED" %}</a>
                          <ul>
                            <li><a href="{% url 'careers:career_list' %}">{% trans "CAREERS" %}</a></li>
                            <li><a href="{% url 'jobs:volunteer' %}">{% trans "JOIN US AS VOLUNTEER" %}</a></li>
                          </ul>
                        </li>
                        <li><a href="{% url 'jobs:contact' %}">{% trans "CONTACT US" %}</a></li>

                        <li class="dropdown"><a href="">{% trans "LANGUAGE" %}</a>
                          <ul>
                            <li> <form action="{% url 'set_language' %}"   method="post">
                              {% csrf_token %}
                              {% get_current_language as LANGUAGE_CODE %}                                         
                              <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                              {% if LANGUAGE_CODE == 'ar' %}
                                  <button type='submit' name='language' value='en' class="theme-btn btn-style-ones" >
                                      <span class="btn-title" style="padding-top:8px">English</span>
                                  </button>
                              {% else %}
                                  <button type='submit' name='language' value='ar' class="theme-btn btn-style-ones">
                                      <span class="btn-title">العربيه</span>
                                  </button>
                              {% endif %}
                          </form></li>
                            <li></li>
                          </ul>
                        </li>

                                                                           
                    </ul>
                    
                </div>
            </nav>
                <!-- Main Menu End-->

                <div class="donate-link">
                  <a href="{% url 'jobs:donate' %}" class="theme-btn btn-style-one"
                  ><span class="btn-title">{% trans "Donate Now" %}</span></a
                >
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--End Header Upper-->

        <!-- Sticky Header  -->
        <div class="sticky-header">
          <div class="auto-container clearfix">
            <!--Logo-->
            <div class="logo pull-left">
              <a href="{% url 'jobs:index' %}"  title=""
                ><img src="{% static 'careers/images/logo.png' %}" alt="" title="" 
                style="height:50px; width:60px;"
              /></a>
            </div>
            <!--Right Col-->
            <div class="pull-right">
              <!-- Main Menu -->
              <nav class="main-menu clearfix">
                <!--Keep This Empty / Menu will come through Javascript-->
              </nav>
              <!-- Main Menu End-->
            </div>
          </div>
        </div>
        <!-- End Sticky Menu -->

        <!-- Mobile Menu  -->
        <div class="mobile-menu">
         
          <div class="menu-outer">
            <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
          </div>
          <div class="menu-backdrop"></div>
          <div class="close-btn">
            <span class="icon flaticon-cancel"></span>
          </div>

          <nav class="menu-box">
            <div class="nav-logo">
              <a href="{% url 'jobs:index' %}"  title=""
              ><img src="{% static 'careers/images/logo.png' %}" alt="" title="" 
              style="height:80px; width:80px;"
            /></a>
            </div>
            <div class="menu-outer">
              <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
            </div>
            <!--Social Links-->
           
          </nav>
        </div>
        <!-- End Mobile Menu -->
      </header>
      <!-- End Main Header -->

 {% block body%}
  
{% endblock body%}

    <!-- Main Footer -->
    <footer class="main-footer">
      <div class="auto-container">
        <!--Widgets Section-->
        <div class="widgets-section">
          <div class="row clearfix">
            <!--Column-->
            <div class="column big-column col-lg-4 col-md-12 col-sm-12">
              <div class="footer-widget logo-widget">
                <div class="widget-content">
                 
                    <div class="text">
                      {% trans       "Ashor Iraqi Foundation for Relief and Development responds to the world’s worst humanitarian crises and helps people to survive and rebuild their lives."  %}
                  </div>
                  <ul class="social-links clearfix"> 
                    <li><a href="https://www.facebook.com/ashuriraq/"><span class="fab fa-facebook-f"></span></a></li>
                    <li><a href="https://twitter.com/ashoriqd?s=11"><span class="fab fa-twitter"></span></a></li>
                    <li><a href="https://www.facebook.com/ashuriraq/"><span class="fab fa-instagram"></span></a></li>
                    <li><a href="https://www.linkedin.com/company/ashuor"><span class="fab fa-linkedin"></span></a></li>
                    <li><a href="https://youtube.com/channel/UCzTbdmJoPxvdnby9Q9JMYJg"><span class="fab fa-youtube"></span></a></li>
                 </ul >
                </div>
              </div>
            </div>
            <!--Column-->
            <div class="big-column col-lg-8 col-md-12 col-sm-12">
              <div class="row clearfix">
                <!--Column-->
                <div class="column col-lg-4 col-md-4 col-sm-12">
                  <div class="footer-widget links-widget">
                    <div class="widget-content">
                      <h3>{% trans "ABOUT AIFRD" %}</h3>
                      <ul>
                        <li><a href="{% url 'jobs:who_we_are' %}">{% trans "WHO WE ARE" %}</a></li>
                        <li><a href="{% url 'blogs:teams' %}">{% trans "OUR TEAM" %}</a></li>
                        <li><a href="{% url 'jobs:vision_mission_value' %}">{% trans "VISION & MISSION"  %}</a></li>
                      </ul>
                    </div>
                  </div>
                </div>

                <!--Column-->
                <div class="column col-lg-4 col-md-4 col-sm-12">
                  <div class="footer-widget links-widget">
                    <div class="footer-widget info-widget">
                      <div class="widget-content">
                        <h3>{% trans "Contact Us" %} </h3>
                        <ul class="contact-info">
                          <li><span class="fa fa-map-marker-alt"></span>{% trans  "Salah Al-Den, Iraq" %}</li>
                        <li><span class="fa fa-phone-alt"></span> <a href="tel:+964 773 1476 198">+964 781 691 8934</a></li>
                          <li>
                            <a href="mailto:representative@aifrd.org"><span class="fa fa-envelope-open"></span>

                              representative@aifrd.org</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                <!--Column-->
                <div class="column col-lg-4 col-md-4 col-sm-12">
                  <div class="footer-widget links-widget">
                    <div class="widget-content">
                      <h3>{% trans "QUICK LINKS" %}</h3>
                      <ul>

                        <li><a href="{% url 'jobs:what_we_are_doing' %}">{% trans "WHAT WE ARE DOING" %}</a></li>
                        <li><a href="{% url 'blogs:stories_and_blogs' %}">{% trans "STORIES & BLOG" %}</a></li>
                        <li><a href="{% url 'jobs:get_involved' %}">{% trans "GET INVOLVED" %}</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>

      <!-- Footer Bottom -->
      <div class="footer-bottom">
        <div class="auto-container">
          <div class="inner">
            <!--Copyright-->
            <div class="copyright">
              {% trans   "Copyrights" %} (c) 2021
              <a href="#">{% trans "Ashor Iraqi Foundation for Relief and Development." %}</a>
               {% trans "All rights reserved." %}
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!--End pagewrapper-->

  <!--Scroll to top-->
  <div class="scroll-to-top scroll-to-target" data-target="html">
    <span class="flaticon-up-arrow"></span>
  </div>
  <script src="{% static 'careers/js/jquery.js' %}"></script>
  <script src="{% static 'careers/js/popper.min.js' %}"></script>
  <script src="{% static 'careers/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'careers/js/jquery-ui.js' %}"></script>
  <script src="{% static 'careers/js/jquery.fancybox.js' %}"></script>
  <script src="{% static 'careers/js/owl.js' %}"></script>
  <script src="{% static 'careers/js/appear.js' %}"></script>
  <script src="{% static 'careers/js/wow.js' %}"></script>

  <script src="{% static 'careers/js/scrollbar.js' %}"></script>
  <script src="{% static 'careers/js/validate.js' %}"></script>
  <script src="{% static 'careers/js/paroller.js' %}"></script>
  <script src="{% static 'careers/js/custom-script.js' %}"></script>
</body>

</html>

careers/templates/career_list.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
      <!-- Page Banner Section -->
      <section class="page-banner">
        {% for i in data %}
        <div class="image-layer" style="background-image: url('{{i.image_bg_career_list}}')"></div>
      
        {% endfor %}
    
        <div class="auto-container">
          <h3>
          {% trans "CAREERS" %}
           
          </h3>
        </div>

        <div class="breadcrumb-box">
          <div class="auto-container">
            <ul class="bread-crumb clearfix">
              <li><a href="{% url 'jobs:index' %}" style="font-size: 12px">{% trans "HOME" %}</a></li>
              <li>
                <a href="{% url 'jobs:get_involved' %}" style="font-size: 12px"
                  >{% trans "GET INVOLVED" %}</a
                >
              </li>
              <!-- <li class="active" style="font-size: 12px">CAREERS</li> -->
            </ul>
          </div>
        </div>
      </section>
      <!--End Banner Section -->

      <!-- News Section Two-->
     




      <section class="career-section-two">
        <div class="auto-container">
          <h3  style="color:#426E94;text-align:center; padding-top:0px; padding-bottom: 50px; background-color:white;">{{message}}</h3>

         <div class="lower-box story-details">
                                <h2 style="font-size:20px; padding-top:0px;"> {% trans "latest careers" %}</h2>
                                <div class="info-box clearfix" style="    margin-bottom: 15px;">
                               
                                        
                                </div>
                              
                            </div>
          <div class="row clearfix">
              <div class="inner">
            
                  
                    
                  <div class="career-post ">
                    <div class="post-thumb">{% for career in careers %}
                    <!--
 <a href="{% url 'careers:career_detail' career.id %}">                     
      <figure class="thumb">
  <img src="{{career.image_career_details.url}}" alt="" style="width:90px;height: 85px;"/>
                        </figure>
                      </a>
                    </div> -->
                    <div  class="careerDes">
                    <h4 class="name" style="font-size:20px; padding-bottom:10px;">  {% if LANGUAGE_CODE == 'en' %} {{career.title}}
                      {% elif LANGUAGE_CODE == 'ar' %} {{career.title_ar}} {% endif %}  </h4>
                 
                    <p> {% if LANGUAGE_CODE == 'en' %} {{career.description}}
                      {% elif LANGUAGE_CODE == 'ar' %} {{career.description_ar}} {% endif %}</p> 
                 
                    <div class="post-info">
                      {% if LANGUAGE_CODE == 'en' %} {{career.location}}
                      {% elif LANGUAGE_CODE == 'ar' %} {{career.location_ar}} {% endif %} ,   {% if LANGUAGE_CODE == 'en' %} {{career.governorate}}
                      {% elif LANGUAGE_CODE == 'ar' %} {{career.governorate_ar}} {% endif %}  &ensp;|&ensp; {{career.posted|date:'d M o'}}  &ensp;
                          <a href="{% url 'careers:career_detail' career.id %}" class="reply-btn" style="font-weight: bold;">{% trans "READ MORE" %}</a>
                    </div>
                    {% endfor %}
                  </div>
                
                  
                 
             
              </div>
            </div>
            <!--Right Column-->
          </div>
        </div>
      </section>
      <!-- Main Footer -->
      {% endblock body %}