aifrd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from jobs.views import ApplicationList, ApplicationRetrieveDestroy
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _



urlpatterns = [
    # django rest api
    path('api/applications', ApplicationList.as_view()),
    path('api/applications/<int:pk>', ApplicationRetrieveDestroy.as_view()),
    path('api-auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('jobs.urls', namespace='jobs')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('careers/', include('careers.urls', namespace='careers')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



admin.site.site_url = None
admin.site.site_header = 'HuminImp Administration'

blogs/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('stories_and_blogs/', views.stories_and_blogs, name='stories_and_blogs'),
    path('teams/', views.teams, name='teams'),


    path('stories/', views.stories_list, name='story'),
    path('story_detail/<int:id>', views.stories_detail, name='stories_detail'),

    # api
    path('api/stories', api.stories_api, name='stories_api'),
    path('api/stories/<int:id>', api.story_detail_api, name='story_detail_api'),


    # class based views
    path('api/v2/stories', api.StoryDetailListApi.as_view(),
         name='StoryDetailListApi'),
    path('api/v2/stories/<int:id>',
         api.StoryDetailDetail.as_view(), name='StoryDetailDetail'),
]

careers/urls.py
from django.urls import include, path

from . import views
from . import api


app_name = 'careers'

urlpatterns = [
    path('careerlist/', views.career_list, name='career_list'),
    path('careerdetail/<int:id>', views.career_detail, name='career_detail'),

    # api
    path('api/careers', api.career_list_api, name='career_list_api'),
    path('api/careers/<int:id>', api.career_detail_api, name='career_detail_api'),
    path('api/careerForm/<str:carrer_name>', views.careerForm, name='careerForm'),

    # class based views
    path('api/v2/careers', api.CareerDetailListApi.as_view(), name='career_list_api'),
    path('api/v2/careers/<int:id>',
         api.CareerDetailDetail.as_view(), name='career_detail_api'),
]

jobs/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from . import views
from . import api

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('applicantsList/', views.applicantsList, name='applicantsList'),
    path('volunteer/', views.volunteerForm, name='volunteer'),
    path('reply/', views.reply, name='reply'),
    path('donate/', views.donate, name='donate'),
    path('contact/', views.contact, name='contact'),
    path('vision_mission_value/', views.vision_mission_value,
         name='vision_mission_value'),
    path('about/', views.about, name='about'),
    path('who_we_are/', views.who_we_are, name='who_we_are'),
    path('get_involved/', views.get_involved, name='get_involved'),
    
    path('what_we_are_doing/', views.what_we_are_doing, name='what_we_are_doing'),
    path('what_we_are_doing_details/<int:id>', views.what_we_are_doing_details,
         name='what_we_are_doing_details'),

    # api
    path('api/what_do', api.what_do_api, name='what_do_api'),
    path('api/what_do_detail/<int:id>',
         api.what_do_detail_api, name='what_do_detail_api'),

    # class based views
    path('api/v2/what_do', api.WhatWeAreDoingDetailListApi.as_view(),
         name='WhatWeAreDoingDetailListApi'),
    path('api/v2/what_do_detail/<int:id>',
         api.WhatWeAreDoingDetailDetail.as_view(), name='WhatWeAreDoingDetailDetail'),

]

jobs/views.py
from email.message import EmailMessage
from django.shortcuts import redirect, render
from django.http import HttpResponse
from rest_framework import generics, permissions
from .models import Application, Replay, Slider,  VisionMissionValue, Volunteer, WhatWeAreDoingBackgroundImage, WhoWeAre, Index, Donate, WhatWeAreDoingDetail, About, GetInvolved
from .serializers import ApplicationSerializer, ReplaySerializer, SliderSerializer, VisionMissionValueSerializer, WhoWeAreSerializer, VolunteerSerializer, IndexSerializer, DonateSerializer, WhatWeAreDoingDetailSerializer, AboutSerializer, GetInvolvedSerializer
from django.http import HttpRequest
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from .filters import WhatWeAreDoingDetailFilter
from django.core.paginator import Paginator
from django.utils.translation import get_language, activate

from blogs.models import StoryDetail
from django.core.mail import send_mail,  EmailMessage

class ApplicationList(generics.ListCreateAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save()


class ApplicationRetrieveDestroy(generics.RetrieveDestroyAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer
    permission_classes = [permissions.IsAuthenticated]


renderer_classes = (JSONRenderer, TemplateHTMLRenderer,)
template_name = "applicantsList.html"


def applicantsList(request):
    """Renders the applicants list page."""
    assert isinstance(request, HttpRequest)
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer(queryset, many=True)

    full_name = request.GET.get('full_name')
    email = request.GET.get('email')
    phone = request.GET.get('phone')
    region = request.GET.get('region')
    address = request.GET.get('address')
    gender = request.GET.get('gender')
    english = request.GET.get('english')
    arabic = request.GET.get('arabic')
    kurdish = request.GET.get('kurdish')
    cover_letter = request.GET.get('cover_letter')
    upload_cv = request.GET.get('upload_cv')

    application = Application.objects.create(full_name=full_name,
                                             email=email,
                                             phone=phone,
                                             region=region,
                                             address=address,
                                             gender=gender,
                                             english=english,
                                             arabic=arabic,
                                             kurdish=kurdish,
                                             cover_letter=cover_letter,
                                             upload_cv=upload_cv,)

    return render(request, 'applicantsList.html',
                  {
                      'data': serializer_class.data,
                  }
                  )


def volunteer(request):
    """Renders the create volunteer page."""
    assert isinstance(request, HttpRequest)
    queryset = Volunteer.objects.all()
    serializer_class = VolunteerSerializer(queryset, many=True)

    return render(request, 'volunteer.html',
                  {
                      'data': serializer_class.data,
                  }
                  )
def reply(request):
    """Renders the create replay page."""
    assert isinstance(request, HttpRequest)
    queryset = Replay.objects.all()
    serializer_class = ReplaySerializer(queryset, many=True)

    return render(request, 'reply.html',
                  {
                      'data': serializer_class.data,
                  }
                  )

def index(request):
    assert isinstance(request, HttpRequest)
    queryset = Index.objects.all()
    serializer_class = IndexSerializer(queryset, many=True)

    stories = StoryDetail.objects.all()
    whatWeDo = WhatWeAreDoingDetail.objects.all()

    # Show many contacts per page for stories
    paginator_story = Paginator(stories, 10000000000000000)
    page_number_story = request.GET.get('page')
    page_obj_story = paginator_story.get_page(page_number_story)

    # Show many contacts per page for what we are doing
    paginator = Paginator(whatWeDo, 10000000000000000)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    slider_show = Slider.objects.all()[:4]
    context = {
        'data': serializer_class.data,
        'slider_show': slider_show,
        'whatWeDoss': page_obj,
        'stories': page_obj_story,
    }
    return render(request, 'index.html', context)



def donate(request):
    """Renders the create volunteer page."""
    assert isinstance(request, HttpRequest)
    queryset = Donate.objects.all()
    serializer_class = DonateSerializer(queryset, many=True)

    return render(request, 'donate.html',
                  {
                      'data': serializer_class.data,
                  }
                  )


def contact(request):
    if request.method == 'POST':
        print("hello")
        name = request.POST.get('full_name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        data = {
            'name': name,
            'phone' : phone,
            'email' : email,
            'subject' : subject,
            'message' : message,
        }
        print(data)
      
        message = ''' 
        New message :{}
        From: {}
        '''.format(data['message'], data['email'])

        if subject and message and email:
            try:
                send_mail(data['subject'], message, from_email= 'info@ashuor.org',recipient_list= ['contact@ashuor.org'],  fail_silently=False)

            except  Exception as error:
                print("error")
                print(error)
                return HttpResponse('Invalid header found.')
    return render(request, 'contact.html')

def volunteerForm(request):
    if request.method == 'POST':
        print("hello")
        name = request.POST.get('full_name')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        region = request.POST.get('region')
        address = request.POST.get('address')
        upload_cv = request.FILES.get('upload_cv')
        English = request.POST.get('English')
        Arabic = request.POST.get('Arabic')
        Kurdish = request.POST.get('Kurdish')
        languages = {"English": English,
        "Arabic":Arabic,
        "Kurdish":Kurdish
        }
        cover_letter = request.POST.get('cover_letter')
        # print(select_language)
        select_language = []

        for language in languages:
            print(language)
            if languages[language] != None:
                select_language.append(language)
        data = {
            'name': name,
            'gender' : gender,
            'email' : email,
            'phone' : phone,
            'region' : region,

            'address': address,
            'upload_cv' : upload_cv,
            'select_language' : select_language,
            'cover_letter' : cover_letter,
        }
        print(data)
        print("hello")
        message = ''' 
        New applicant :{}
        From: {}
        Phone: {}
        Region: {}
        Gender: {}
        Address:{}
        CV: {}
        Language:{}
        Cover_letter: {}


        '''.format(data['name'], data['email'], data['phone'], data['region'], data['gender'], data['address'], data['upload_cv'], data['select_language'], data['cover_letter'])

        if name and gender and email  and phone and  region  and  address and   upload_cv  and cover_letter:

            email = EmailMessage(
                              data['name'],    
                              message,
                              'info@ashuor.org', ['volunteer@ashuor.org'],)
                          
            if request.FILES:
                            uploaded_file = request.FILES['upload_cv'] # file is the name value which you have provided in form for file field
                            email.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
                            email.send()
            #     send_mail(data['carrer_name'], message, from_email= 'info@ashuor.org',recipient_list= ['hr@aifrd.org'],  fail_silently=False)
            #     send_mail.attach(message. attach.read(), )
            #     send_mail.send()
            # except  Exception as error:
            #     return HttpResponse('Invalid header found.')
    return render(request, 'volunteer.html')


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
    finally:
        activate(cur_language)

def what_we_are_doing(request):
    """Renders the create what_we_are_doing page."""
    whatWeDo = WhatWeAreDoingDetail.objects.all()

    # filters
    myfilter = WhatWeAreDoingDetailFilter(request.GET, queryset=whatWeDo)
    whatWeDo = myfilter.qs
    bg_image_what_we_are_doing = WhatWeAreDoingBackgroundImage.objects.all()
     
    # Show many contacts per page.
    paginator = Paginator(whatWeDo, 10000000000000000)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if whatWeDo:
        context = {'whatWeDoss': page_obj,
                   'myfilter': myfilter,
                   'bg_image_what_we_are_doing':bg_image_what_we_are_doing}  # template name

    else:
        context = {'message': "There are no WhatWeDo available at the moment."}
    return render(request, 'what_we_are_doing.html', context)


def what_we_are_doing_details(request, id):
    """Renders the create what_we_are_doing_details page."""

jobs/templates/applicantsList.html
<html>
    {% load static %}
<body>
    <h1>applicants</h1>
    <ul>
            {% for d in data %}
                <li>id: {{ d.id }}</li>  
                <li>full_name: {{ d.full_name }}</li>  
                <li>email: {{ d.email }}</li>
                <li>phone: {{ d.phone }}</li>
                <li>region: {{ d.region }}</li>
                <li>gender: {{ d.gender }}</li>
                <li>english: {{ d.english }}</li>
                <li>arabic: {{ d.arabic }}</li>
                <li>kurdish: {{ d.kurdish }}</li>
                <li>cover_letter: {{ d.cover_letter }}</li>
                <li>upload_cv: <img src={{d.upload_cv}}>{{d.upload_cv}}</li>
                <br>
            {% endfor %}
    </ul>
</body></html>

jobs/templates/contactList.html
<html>
    {% load static %}
<body>
    <h1>contacts</h1>
    <ul>
            {% for d in data %}
                <li>id: {{ d.id }}</li>  
                <li>full_name: {{ d.full_name }}</li>  
                <li>email: {{ d.email }}</li>
                <li>phone: {{ d.phone }}</li>
                <li>subject: {{ d.subject }}</li>
                <li>message: {{ d.message }}</li>
                <br>
            {% endfor %}
    </ul>
</body></html>

jobs/templates/get_involved.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Page Banner Section -->
<section class="page-banner">
  {% for i in data %}
  <div class="image-layer" style="background-image: url('{{i.image_bg_getInvolved}}')"></div>

  {% endfor %}
  <div class="auto-container">
    <h2>{% trans "Spread The Love & Get Involved!" %}</h2>
    <div class="text">{% trans "Join Us To Save The World Of Humanitarian And Feel Happy To Support" %}</div>

  </div>

  <div class="breadcrumb-box">
    <div class="auto-container">
      <ul class="bread-crumb clearfix">
        <li><a class="dirBanner" href="{% url 'jobs:index' %}" style="font-size: 12px">{% trans "HOME" %}</a></li>
        <li class="active">{% trans "GET INVOLVED" %}</li>
      </ul>
    </div>
  </div>
</section>
<!--End Banner Section -->

<section class="featured-section center" style="padding-top:80px">

  <div class="auto-container">

    <div class="featured-row" >
      <div class="row clearfix">

        <!--Featured Block Two-->
        <div class="featured-block-two col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="0ms">
          <div class="inner-box">
            <div class="image-box">
              <figure class="image"><a href="{% url 'careers:career_list' %}">
                  {% for i in data %}
                  <img src="{{i.image_careers_getinvolved}}" height="250px"  alt="">

                </a></figure>
            </div>
            <div class="lower-content">
              <h3><a href="{% url 'careers:career_list' %}">{% trans "CAREERS" %}</a></h3>
              <div class="text">{% if LANGUAGE_CODE == 'en' %}{{i.text_careers_getinvolved}}
                {% elif LANGUAGE_CODE == 'ar' %}{{i.text_careers_getinvolved_ar}}{% endif %} </div>

              <div class="link-box"><a href="{% url 'careers:career_list' %}" class="theme-btn btn-style-four"><span
                    class="btn-title">{% trans "Discover Our Careers" %}</span></a></div>
            </div>
          </div>
        </div>

        <!--Featured Block Two-->
        <div class="featured-block-two col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="300ms">
          <div class="inner-box">
            <div class="image-box">
              <figure class="image"><a href="{% url 'jobs:volunteer' %}">
                  {% for i in data %}
                  <img src="{{i.image_joinus_getinvolved}}"  width="260px" height="260px" alt="" >{% endfor %}
                </a></figure>
            </div>
            <div class="lower-content">
              <h3><a href="{% url 'jobs:volunteer' %}">{% trans "JOIN US AS VOLUNTEER" %}</a></h3>
              <div class="text">{% if LANGUAGE_CODE == 'en' %}{{i.text_joinus_getinvolved}}
                {% elif LANGUAGE_CODE == 'ar' %}{{i.text_joinus_getinvolved_ar}}{% endif %} </div>
              {% endfor %}
              <div class="link-box"><a href="{% url 'jobs:volunteer' %}" class="theme-btn btn-style-four"><span
                    class="btn-title">{% trans "Join Us" %}</span></a></div>
            </div>
          </div>
        </div>

      </div>
    </div>


  </div>
</section>



{% endblock body %}

jobs/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Banner Section -->
<section class="banner-section">

  <div class="banner-carousel kausid-carousel owl-theme owl-carousel"
    data-options='{"loop": true, "margin": 0, "autoheight":true,  "lazyload":true, "nav": true, "dots": true, "autoplay": true, "autoplayTimeout": 6000, "smartSpeed": 300, "responsive":{ "0" :{ "items": "1" }, "768" :{ "items" : "1" } , "1000":{ "items" : "1" }}}'>
    {% for slider in slider_show %}
    <!-- Slide Item -->
    <div class="slide-item { % if forloop.counter0 == 0 %} active {% endif % }">
      <div class="image-layer" style="background-image: url('{{slider.slide_image_index.url}}')"></div>

      <div class="auto-container">
        <div class="content-box">
          <div class="content">
            <div class="">
             
              <div class="sub-title">{% if LANGUAGE_CODE == 'en' %}{{slider.slide_subtitle_index}}
                {% elif LANGUAGE_CODE == 'ar' %}{{slider.slide_subtitle_index_ar}}{% endif %}</div>
              <h2>{% if LANGUAGE_CODE == 'en' %}{{slider.slide_title_index}}
                {% elif LANGUAGE_CODE == 'ar' %}{{slider.slide_title_index_ar}}{% endif %}</h2>

            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- Slide Item -->

  </div>
</section>
<!--End Banner Section -->
<!--About Section Four-->
<section class="about-section-four">

  <div class="auto-container">
    <div class="row clearfix">
      <!--Text Column-->
      <div class="text-column col-lg-6 col-md-12 col-sm-12">
        <div class="inner">
          <div class="sec-title">
            <div class="sub-title">
              <h3 style="font-size:16px"> {% trans "Since 2015" %}<h3>
            </div>
            <h2 style="font-size:25px">{% trans "Ashor Iraqi Foundation for Relief and Development" %}</h2>
          </div> {% for i in data %}
          <div class="text" style="padding-top: 10px;">{% if LANGUAGE_CODE == 'en' %}{{i.text_about_index}}
            {% elif LANGUAGE_CODE == 'ar' %}{{i.text_about_index_ar}}{% endif %}</div> {% endfor %}
          <div class="link-box"><a href="{% url 'jobs:about' %}" class="default-link"> {% trans "READ MORE" %}</a></div>

        </div>
      </div>
      <!--Image Column-->
      <div class="image-column col-lg-6 col-md-12 col-sm-12">
        <div class="inner">
          <div class="image-box">
            <figure class="image">
              {% for i in data %}
              <img src="{{i.image_about_index}}" style="height:358px; width:795.6px;" alt="">
              {% endfor %}
            </figure>
            <div class="caption-box wow fadeInUp" data-wow-delay="0ms">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

<section class="what-we-do causes-section alternate-two news-section">

  <div class="auto-container">
    <div class="" style="padding-bottom:20px;padding-top:40px;text-align:center">
      <h2> {% trans "What We Are Doing" %}</h2>
    </div>
    {% for i in data %}
    <p style="text-align:center;padding-top:20px;padding-bottom:50px;"> {% if LANGUAGE_CODE == 'en' %}{{i.whatDoDetail_text}}
      {% elif LANGUAGE_CODE == 'ar' %}{{i.whatDoDetail_text_ar}}{% endif %}</p>
    {% endfor %}
    <div class="row clearfix">

      {% for whatWeDo in whatWeDoss %}
      {% if forloop.counter < 4 %} <!--Service Block-->
        <div class="service-block col-lg-4 col-md-6 col-sm-12 wow fadeInLeft" data-wow-delay="0ms">

          <div class="inner-box">

            <div class="icon"><span class='{{ whatWeDo.whatDoDetail_icon_name }}'></span></div>

            <h3><a href="{% url 'jobs:what_we_are_doing_details' whatWeDo.id %}">{% if LANGUAGE_CODE == 'en' %}{{whatWeDo.whatDoDetail_name}}
              {% elif LANGUAGE_CODE == 'ar' %}{{whatWeDo.whatDoDetail_name_ar}}{% endif %}</a></h3>
            <div class="text">{% if LANGUAGE_CODE == 'en' %}{{whatWeDo.whatDoDetail_desc1}}
              {% elif LANGUAGE_CODE == 'ar' %}{{whatWeDo.whatDoDetail_desc1_ar}}{% endif %}</div>
            <div class="link-box"><a href="{% url 'jobs:what_we_are_doing_details' whatWeDo.id %}"
                class="theme-btn"> {% trans "Explore" %}</a></div>
          </div>

        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="load-more" style="padding-bottom:30px"><a href="{% url 'jobs:what_we_are_doing' %}"
        class="theme-btn load-more-btn"> {% trans "SEE MORE" %}</a></div>






  </div>
  <div>







</section>
<section class="call-to-action">
  <div class="image-layer" style="background-image: url('images/background/bg-pattern-1.png')"></div>

  <div class="auto-container volunteer">
    <div class="row clearfix">
      <div class="title-column col-xl-9 col-lg-12 col-md-12 col-sm-12">
        <h2>
          {% trans "Become a vital part of Ashor Iraqi Foundation for Relief and Development & make a real difference to lives of many!" %}
        </h2>
      </div>
      <div class="link-column col-xl-3 col-lg-12 col-md-12 col-sm-12">
        <div class="link-box">
          <a href="{% url 'jobs:volunteer' %}" class="theme-btn btn-style-two"><span class="btn-title">{% trans "JOIN US AS A VOLUNTEERS" %}</span></a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="stories-section" style="padding-top:80px">

  <div class="auto-container">
    <div class="row clearfix">

      <div class="image-column col-lg-6 col-md-12 col-sm-12">
        <div class="inner">
          <div class="image-box">
            <figure class="image">
              {% for i in data %}
              <img src="{{i.image_story_index}}" style="height:358px; width:795.6px;" alt="">
              {% endfor %}
            </figure>
            <div class="caption-box wow fadeInUp" data-wow-delay="0ms">
            </div>
          </div>
        </div>
      </div>
      <!--Text Column-->
      <div class="text-column col-lg-6 col-md-12 col-sm-12">
        <div class="inner">
          <div class="sec-title"></div>
          <h2 style="font-size:36px">{% trans "OUR STORIS" %}</h2>
        </div> {% for i in data %}
        <div class="text" style="padding-top:20px">{% if LANGUAGE_CODE == 'en' %}{{i.text_story_index}}
          {% elif LANGUAGE_CODE == 'ar' %}{{i.text_story_index_ar}}{% endif %}</div> {% endfor %}
        <div class="link-box"> <a href="{% url 'blogs:story' %}" class="default-link" style="padding-top:20px;">{% trans "VIEW ALL STORIES" %}</a></div>

      </div>
    </div>

  </div>
  </div>

</section>
<section class="stories-section load-more-section" data-load-number="2">
  <div class="auto-container">
    <div class="row clearfix " style="padding-top:80px">

      {% for story in stories %}
      {% if forloop.counter < 4 %} <div class=" col-lg-4 col-md-6 col-sm-12">

        <aside class="stories">
          <!-- Event Widget -->
          <div class="stories-widget story-widget">
            <div class="widget-inner">
              <div class="widget-content">
                <figure class="image">


                  <img src="{{story.story_image_one.url}}" style="height:176px; width:270px;" alt="" title="" />
                </figure>
                <div class="lower-box story-details">
                  <div class="info-box clearfix">
                    <div class="cause-info">
                      <ul class="clearfix">
                        <li><span class="far flaticon-calendar"></span> <span>{{story.story_date|date:'d M o'}}</span>
                        </li>
                        <li><span class="fa fa-map-marker-alt"></span> {% if LANGUAGE_CODE == 'en' %}{{story.story_location}}
                          {% elif LANGUAGE_CODE == 'ar' %}{{story.story_location_ar}}{% endif %}</li>
                      </ul>
                    </div>


                  </div>

                </div>
                <h4>
                  <a href="{% url 'blogs:stories_detail' story.id %}">{% if LANGUAGE_CODE == 'en' %}{{story.story_name}}
                    {% elif LANGUAGE_CODE == 'ar' %}{{story.story_name_ar}}{% endif %}</a>
                </h4>
                <p> {% if LANGUAGE_CODE == 'en' %}{{story.story_desc1 }}
                  {% elif LANGUAGE_CODE == 'ar' %}{{story.story_desc1_ar}}{% endif %}
                </p>
                <ul class="info">
               
                <li>
                 <div class="link-box" style="padding-left:4px;font-size:12px">
                   <a href="{% url 'blogs:stories_detail' story.id %}" class="default-link">{% trans "READ MORE" %}</a></div>
</li>
               
              </ul>
              </div>
            </div>
          </div>
        </aside>
    </div>

    {% endif %} {% endfor %}
  </div>
  </div>
</section>


{% endblock body %}

jobs/templates/reply.html
{% extends 'base2.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!-- End Main Header -->




  <!--Featured Blocks-->
  <div class="featured-blocks vission_mission_section">
    <div class="row clearfix">
    
      <!--Featured Block-->
      <div class="featured-block col-lg-12 col-md-12 col-sm-12">
        <div class="inner-box">
          <div class="iconss">
            <h3 style="text-align: center; padding-top: 50px;" class="replay-text-arabic"> {% trans "Thank You!" %}</h3>
            <div style="text-align: center;" class="icon">
              <span  class="flaticon-email-1"></span>
            </div>
          
            <div style="text-align: center;" class="replay-text-arabic-para">
              {% trans "For choosing Ashor Iraqi Foundation For Relief And Development, We’ll get back to you about your order as soon as possible." %}
              <p style="text-align: center; ">
                {% trans "Having trouble?" %} <a href="{% url 'jobs:contact' %}">{% trans "Contact us" %}</a>
              </p>
            </div>
            <div class="donate-link" style="text-align: center; padding-top: 30px;">
                <a href="{% url 'jobs:index' %}" class="theme-btn btn-style-one"
                ><span class="btn-title">{% trans "back to home page" %}</span></a
              >
           
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</div>
</section>

{% endblock body %}




   